# Generated by Django 4.2.2 on 2023-06-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='queue',
            field=models.IntegerField(default=0),
        ),
    ]
